import { MigrationInterface, QueryRunner } from "typeorm";

export class ProjectSetup1775385233564 implements MigrationInterface {
    name = 'ProjectSetup1775385233564'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`CREATE TABLE "users" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_by" uuid, "deleted_at" TIMESTAMP WITH TIME ZONE, "firstName" character varying(100) NOT NULL, "lastName" character varying(100) NOT NULL, "email" character varying(255) NOT NULL, "passwordHash" character varying NOT NULL, "phone_encrypted" text, "is_active" boolean NOT NULL DEFAULT true, "is_email_verified" boolean NOT NULL DEFAULT false, "failed_login_attempts" integer NOT NULL DEFAULT '0', "locked_until" TIMESTAMP WITH TIME ZONE, "last_login_at" TIMESTAMP WITH TIME ZONE, "last_login_ip" character varying(45), "totp_secret" text, "is_two_factor_enabled" boolean NOT NULL DEFAULT false, CONSTRAINT "UQ_97672ac88f789774dd47f7c8be3" UNIQUE ("email"), CONSTRAINT "PK_a3ffb1c0c8416b9fc6f907b7433" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_97672ac88f789774dd47f7c8be" ON "users" ("email") `);
        await queryRunner.query(`CREATE TABLE "roles" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(50) NOT NULL, "description" text, "is_system" boolean NOT NULL DEFAULT false, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_648e3f5447f725579d7d4ffdfb7" UNIQUE ("name"), CONSTRAINT "PK_c1433d71a4838793a49dcad46ab" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_648e3f5447f725579d7d4ffdfb" ON "roles" ("name") `);
        await queryRunner.query(`CREATE TABLE "permissions" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "module" character varying(50) NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_48ce552495d14eae9b187bb6716" UNIQUE ("name"), CONSTRAINT "PK_920331560282b8bd21bb02290df" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_48ce552495d14eae9b187bb671" ON "permissions" ("name") `);
        await queryRunner.query(`CREATE TABLE "refresh_tokens" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "user_id" uuid NOT NULL, "token_hash" character varying(128) NOT NULL, "device_info" jsonb, "ip_address" character varying(45), "session_id" uuid NOT NULL, "is_revoked" boolean NOT NULL DEFAULT false, "revoked_at" TIMESTAMP WITH TIME ZONE, "revoked_reason" character varying(255), "expires_at" TIMESTAMP WITH TIME ZONE NOT NULL, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_7d8bee0204106019488c4c50ffa" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_ba3bd69c8ad1e799c0256e9e50" ON "refresh_tokens" ("expires_at") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_a7838d2ba25be1342091b6695f" ON "refresh_tokens" ("token_hash") `);
        await queryRunner.query(`CREATE INDEX "IDX_3ddc983c5f7bcf132fd8732c3f" ON "refresh_tokens" ("user_id") `);
        await queryRunner.query(`CREATE TABLE "police_stations" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_by" uuid, "code" character varying(20) NOT NULL, "name" character varying(200) NOT NULL, "address" text, "region" character varying(100), "region_id" uuid, "parent_station_id" uuid, "commanding_officer_id" uuid, "phone" character varying(30), "email" character varying(255), "is_active" boolean NOT NULL DEFAULT true, "complaint_count" integer NOT NULL DEFAULT '0', "coordinates" jsonb, CONSTRAINT "UQ_66e88c2f16f4a8d3aa2321ea1a0" UNIQUE ("code"), CONSTRAINT "PK_8197d507287440c2ab9b220b441" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_830a5640e559f29067cc4985ac" ON "police_stations" ("region_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_66e88c2f16f4a8d3aa2321ea1a" ON "police_stations" ("code") `);
        await queryRunner.query(`CREATE TYPE "public"."escalation_records_reason_enum" AS ENUM('sla_breach', 'severity_upgrade', 'supervisor_request', 'citizen_appeal', 'oversight_referral', 'repeated_officer')`);
        await queryRunner.query(`CREATE TABLE "escalation_records" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_by" uuid, "complaint_id" uuid NOT NULL, "escalated_by_id" uuid NOT NULL, "escalated_to_id" uuid, "reason" "public"."escalation_records_reason_enum" NOT NULL, "description" text, "status" character varying(30) NOT NULL DEFAULT 'pending', "due_date" TIMESTAMP WITH TIME ZONE, "review_notes" text, "reviewed_by_id" uuid, "reviewed_at" TIMESTAMP WITH TIME ZONE, "disciplinary_recommendation" text, CONSTRAINT "PK_195f5eb50488ee9bea2a0aae2e1" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_d70989ea1ee2b4e6e5548fdb15" ON "escalation_records" ("due_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_43201337271442fa404765d7bb" ON "escalation_records" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_8f2f8bd600c9e1d07f8343a33c" ON "escalation_records" ("escalated_by_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_c0aea07014a01aa7ec7e1609f0" ON "escalation_records" ("complaint_id") `);
        await queryRunner.query(`CREATE TABLE "officers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_by" uuid, "badge_number" character varying(30) NOT NULL, "service_number" character varying(30), "first_name" character varying(100) NOT NULL, "last_name" character varying(100) NOT NULL, "rank" character varying(50) NOT NULL, "unit" character varying(100), "station_id" uuid, "is_active" boolean NOT NULL DEFAULT true, "joined_date" date, "complaint_count" integer NOT NULL DEFAULT '0', "metadata" jsonb, CONSTRAINT "UQ_f25c755da01b839dcf39b674ffa" UNIQUE ("badge_number"), CONSTRAINT "PK_51b2f6e36c3acee541c66bf4047" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a2e938acd9bad6c1834af39e19" ON "officers" ("rank") `);
        await queryRunner.query(`CREATE INDEX "IDX_adcfd81394978d443ec6fe39d1" ON "officers" ("station_id") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_f25c755da01b839dcf39b674ff" ON "officers" ("badge_number") `);
        await queryRunner.query(`CREATE TABLE "complaint_officers" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "complaint_id" uuid NOT NULL, "officer_id" uuid NOT NULL, "role" character varying(50) NOT NULL DEFAULT 'accused', "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "PK_63ca4d96eb7d4629a47e4da30ae" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_94fdca3c049f3b33844b9a03c8" ON "complaint_officers" ("complaint_id", "officer_id") `);
        await queryRunner.query(`CREATE TYPE "public"."notifications_type_enum" AS ENUM('email', 'sms', 'in_app', 'push')`);
        await queryRunner.query(`CREATE TYPE "public"."notifications_status_enum" AS ENUM('pending', 'sent', 'delivered', 'failed', 'retrying')`);
        await queryRunner.query(`CREATE TABLE "notifications" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "recipient_id" uuid, "recipient_email" character varying(255), "recipient_phone" character varying(30), "type" "public"."notifications_type_enum" NOT NULL, "subject" character varying(200) NOT NULL, "body" text NOT NULL, "status" "public"."notifications_status_enum" NOT NULL DEFAULT 'pending', "sent_at" TIMESTAMP WITH TIME ZONE, "failed_at" TIMESTAMP WITH TIME ZONE, "failure_reason" text, "retry_count" integer NOT NULL DEFAULT '0', "max_retries" integer NOT NULL DEFAULT '3', "reference_type" character varying(50), "reference_id" uuid, "metadata" jsonb, CONSTRAINT "PK_6a72c3c0f683f6462415e653c3a" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_77ee7b06d6f802000c0846f3a5" ON "notifications" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_aef1c7aef3725068e5540f8f00" ON "notifications" ("type") `);
        await queryRunner.query(`CREATE INDEX "IDX_92f5d3a7779be163cbea7916c6" ON "notifications" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_5332a4daa46fd3f4e6625dd275" ON "notifications" ("recipient_id") `);
        await queryRunner.query(`CREATE TYPE "public"."complaints_status_enum" AS ENUM('draft', 'submitted', 'acknowledged', 'under_review', 'assigned', 'under_investigation', 'awaiting_response', 'escalated', 'resolved', 'closed', 'rejected', 'withdrawn')`);
        await queryRunner.query(`CREATE TYPE "public"."complaints_severity_enum" AS ENUM('low', 'medium', 'high', 'critical')`);
        await queryRunner.query(`CREATE TYPE "public"."complaints_category_enum" AS ENUM('excessive_force', 'misconduct', 'corruption', 'discrimination', 'harassment', 'negligence', 'unlawful_arrest', 'abuse_of_power', 'property_damage', 'unprofessional_conduct', 'delayed_response', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."complaints_source_enum" AS ENUM('citizen_direct', 'anonymous', 'third_party', 'internal', 'oversight_referral', 'media')`);
        await queryRunner.query(`CREATE TYPE "public"."complaints_channel_enum" AS ENUM('web', 'mobile', 'phone', 'in_person', 'email', 'letter')`);
        await queryRunner.query(`CREATE TABLE "complaints" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_by" uuid, "reference_number" character varying(30) NOT NULL, "title" text NOT NULL, "description" text NOT NULL, "status" "public"."complaints_status_enum" NOT NULL DEFAULT 'submitted', "severity" "public"."complaints_severity_enum" NOT NULL DEFAULT 'medium', "category" "public"."complaints_category_enum" NOT NULL, "source" "public"."complaints_source_enum" NOT NULL DEFAULT 'citizen_direct', "channel" "public"."complaints_channel_enum" NOT NULL DEFAULT 'web', "is_anonymous" boolean NOT NULL DEFAULT false, "citizen_user_id" uuid, "complainant_name_encrypted" text, "complainant_email_encrypted" text, "complainant_phone_encrypted" text, "complainant_address_encrypted" text, "incident_date" date, "incident_location" text, "station_id" uuid, "tracking_token" character varying(64), "resolution_summary" text, "closed_at" TIMESTAMP WITH TIME ZONE, "sla_due_date" TIMESTAMP WITH TIME ZONE, "is_overdue" boolean NOT NULL DEFAULT false, "idempotency_key" character varying(64), "version" integer NOT NULL DEFAULT '1', CONSTRAINT "UQ_0119fb6d3ef9bec0c4f3de4721e" UNIQUE ("reference_number"), CONSTRAINT "UQ_e3b80fdb33297c6a12849992467" UNIQUE ("tracking_token"), CONSTRAINT "UQ_40ffcc789fc678da04328bb597e" UNIQUE ("idempotency_key"), CONSTRAINT "PK_4b7566a2a489c2cc7c12ed076ad" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_af397ec1c0acdfeb72dc8e1fa0" ON "complaints" ("station_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_8c7495e1206503c359c41b6c96" ON "complaints" ("citizen_user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_dab6594090bc04d8ce83a997e8" ON "complaints" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_045cb646312f78bded6507fca5" ON "complaints" ("severity") `);
        await queryRunner.query(`CREATE INDEX "IDX_57f8030602f0e930c4c7b8a7bc" ON "complaints" ("category") `);
        await queryRunner.query(`CREATE INDEX "IDX_208ad761b4359509cd2f43da87" ON "complaints" ("status") `);
        await queryRunner.query(`CREATE UNIQUE INDEX "IDX_0119fb6d3ef9bec0c4f3de4721" ON "complaints" ("reference_number") `);
        await queryRunner.query(`CREATE TABLE "complaint_categories_ref" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "name" character varying(100) NOT NULL, "description" text, "is_active" boolean NOT NULL DEFAULT true, "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), CONSTRAINT "UQ_bfbe8aa184950ffecc8774dae15" UNIQUE ("name"), CONSTRAINT "PK_058c9607aa39d615f93024e23f8" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE TABLE "complaint_notes" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_by" uuid, "complaint_id" uuid NOT NULL, "content" text NOT NULL, "is_internal" boolean NOT NULL DEFAULT true, "note_type" character varying(50) NOT NULL DEFAULT 'general', CONSTRAINT "PK_f6d413a9225f2633753fb40abe7" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_c5f7adf7ff580617ee37583943" ON "complaint_notes" ("complaint_id") `);
        await queryRunner.query(`CREATE TYPE "public"."evidence_evidence_type_enum" AS ENUM('document', 'image', 'video', 'audio', 'forensic', 'witness_statement', 'other')`);
        await queryRunner.query(`CREATE TYPE "public"."evidence_access_level_enum" AS ENUM('public', 'restricted', 'confidential', 'classified')`);
        await queryRunner.query(`CREATE TABLE "evidence" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_by" uuid, "complaint_id" uuid NOT NULL, "file_name" character varying(255) NOT NULL, "original_name" character varying(255) NOT NULL, "mime_type" character varying(100) NOT NULL, "file_size" bigint NOT NULL, "storage_path" text NOT NULL, "storage_provider" character varying(20) NOT NULL DEFAULT 'local', "file_hash" character varying(128) NOT NULL, "hash_algorithm" character varying(20) NOT NULL DEFAULT 'sha256', "evidence_type" "public"."evidence_evidence_type_enum" NOT NULL, "access_level" "public"."evidence_access_level_enum" NOT NULL DEFAULT 'restricted', "description" text, "is_malware_scanned" boolean NOT NULL DEFAULT false, "malware_scan_result" character varying(50), "is_integrity_verified" boolean NOT NULL DEFAULT true, CONSTRAINT "PK_b864cb5d49854f89917fc0b44b9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_1cfd367dd1275329cdc58b9024" ON "evidence" ("access_level") `);
        await queryRunner.query(`CREATE INDEX "IDX_71c5d63002a009be1366ed0632" ON "evidence" ("evidence_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_31e7823c6447bed65f6304d59b" ON "evidence" ("complaint_id") `);
        await queryRunner.query(`CREATE TABLE "evidence_chain_of_custody" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "evidence_id" uuid NOT NULL, "actor_id" uuid NOT NULL, "action" character varying(50) NOT NULL, "notes" text, "ip_address" character varying(45), "metadata" jsonb, CONSTRAINT "PK_e3515f56abf8f27c5f01a524a6e" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_010680569c7a7eee0a37801dd4" ON "evidence_chain_of_custody" ("evidence_id") `);
        await queryRunner.query(`CREATE TYPE "public"."complaint_status_history_previous_status_enum" AS ENUM('draft', 'submitted', 'acknowledged', 'under_review', 'assigned', 'under_investigation', 'awaiting_response', 'escalated', 'resolved', 'closed', 'rejected', 'withdrawn')`);
        await queryRunner.query(`CREATE TYPE "public"."complaint_status_history_new_status_enum" AS ENUM('draft', 'submitted', 'acknowledged', 'under_review', 'assigned', 'under_investigation', 'awaiting_response', 'escalated', 'resolved', 'closed', 'rejected', 'withdrawn')`);
        await queryRunner.query(`CREATE TABLE "complaint_status_history" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "complaint_id" uuid NOT NULL, "previous_status" "public"."complaint_status_history_previous_status_enum", "new_status" "public"."complaint_status_history_new_status_enum" NOT NULL, "changed_by_id" uuid NOT NULL, "reason_code" character varying(50), "reason" text, "metadata" jsonb, CONSTRAINT "PK_f1a4835ad43ef2c46d6faa3f256" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_e39f0fb6135bc98a2d60d965a0" ON "complaint_status_history" ("complaint_id", "created_at") `);
        await queryRunner.query(`CREATE TYPE "public"."complaint_assignments_status_enum" AS ENUM('pending', 'accepted', 'in_progress', 'completed', 'reassigned', 'declined')`);
        await queryRunner.query(`CREATE TABLE "complaint_assignments" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "created_by" uuid, "updated_by" uuid, "complaint_id" uuid NOT NULL, "assignee_id" uuid NOT NULL, "assigned_by_id" uuid NOT NULL, "status" "public"."complaint_assignments_status_enum" NOT NULL DEFAULT 'pending', "assignment_reason" text, "sla_due_date" TIMESTAMP WITH TIME ZONE, "is_supervisor_override" boolean NOT NULL DEFAULT false, "completed_at" TIMESTAMP WITH TIME ZONE, "previous_assignment_id" uuid, CONSTRAINT "PK_572e044b03340f077008e56c53c" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_a77c28207a20aa2ad37ce5eca9" ON "complaint_assignments" ("sla_due_date") `);
        await queryRunner.query(`CREATE INDEX "IDX_4fef5beb624cd7bfd0f1401a94" ON "complaint_assignments" ("status") `);
        await queryRunner.query(`CREATE INDEX "IDX_4e2dc6d29a58fb59a9641c4133" ON "complaint_assignments" ("assignee_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_31c8776aa38d6fab44b2f34741" ON "complaint_assignments" ("complaint_id") `);
        await queryRunner.query(`CREATE TYPE "public"."audit_logs_action_enum" AS ENUM('login', 'login_failed', 'logout', 'token_refresh', 'password_change', 'user_created', 'user_updated', 'user_deactivated', 'user_activated', 'role_assigned', 'role_revoked', 'complaint_created', 'complaint_updated', 'complaint_status_changed', 'complaint_assigned', 'complaint_reassigned', 'complaint_escalated', 'complaint_closed', 'complaint_withdrawn', 'evidence_uploaded', 'evidence_accessed', 'evidence_deleted', 'evidence_integrity_check', 'officer_created', 'officer_updated', 'oversight_referral', 'oversight_review', 'disciplinary_recommendation', 'ai_analysis_requested', 'ai_analysis_completed', 'ai_result_reviewed', 'ai_result_overridden', 'config_changed', 'role_created', 'role_updated', 'permission_changed')`);
        await queryRunner.query(`CREATE TABLE "audit_logs" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "actor_id" uuid, "actor_email" character varying(255), "action" "public"."audit_logs_action_enum" NOT NULL, "entity_type" character varying(50) NOT NULL, "entity_id" uuid, "before_state" jsonb, "after_state" jsonb, "ip_address" character varying(45), "user_agent" text, "correlation_id" character varying(64), "outcome" character varying(20) NOT NULL DEFAULT 'success', "failure_reason" text, "metadata" jsonb, CONSTRAINT "PK_1bb179d048bbc581caa3b013439" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_052f6905a83dedf0d5eeb5e69d" ON "audit_logs" ("correlation_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_2cd10fda8276bb995288acfbfb" ON "audit_logs" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_cee5459245f652b75eb2759b4c" ON "audit_logs" ("action") `);
        await queryRunner.query(`CREATE INDEX "IDX_177183f29f438c488b5e8510cd" ON "audit_logs" ("actor_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_7421efc125d95e413657efa3c6" ON "audit_logs" ("entity_type", "entity_id") `);
        await queryRunner.query(`CREATE TYPE "public"."ai_analysis_results_analysis_type_enum" AS ENUM('classification', 'priority_scoring', 'duplicate_detection', 'entity_extraction', 'summarization', 'pattern_detection', 'route_recommendation')`);
        await queryRunner.query(`CREATE TYPE "public"."ai_analysis_results_review_status_enum" AS ENUM('pending', 'accepted', 'rejected', 'overridden')`);
        await queryRunner.query(`CREATE TABLE "ai_analysis_results" ("id" uuid NOT NULL DEFAULT uuid_generate_v4(), "created_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "updated_at" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now(), "complaint_id" uuid NOT NULL, "model_name" character varying(100) NOT NULL, "model_version" character varying(30) NOT NULL, "analysis_type" "public"."ai_analysis_results_analysis_type_enum" NOT NULL, "input_hash" character varying(128) NOT NULL, "output" jsonb NOT NULL, "confidence_score" numeric(5,4), "explanation" text, "recommended_category" character varying(50), "recommended_priority" character varying(20), "duplicate_matches" jsonb, "review_status" "public"."ai_analysis_results_review_status_enum" NOT NULL DEFAULT 'pending', "reviewed_by" uuid, "reviewed_at" TIMESTAMP WITH TIME ZONE, "human_override_reason" text, "processing_time_ms" integer, CONSTRAINT "PK_a628d27356f4fb92c423529e0e9" PRIMARY KEY ("id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_28345c74f19456b00f80c1a9d2" ON "ai_analysis_results" ("created_at") `);
        await queryRunner.query(`CREATE INDEX "IDX_89a7d942bb1fc9e2989c032eca" ON "ai_analysis_results" ("review_status") `);
        await queryRunner.query(`CREATE INDEX "IDX_24d1284269b70adadd4e9d9253" ON "ai_analysis_results" ("analysis_type") `);
        await queryRunner.query(`CREATE INDEX "IDX_7d6df34265c2fae0e64979374d" ON "ai_analysis_results" ("complaint_id") `);
        await queryRunner.query(`CREATE TABLE "user_roles" ("user_id" uuid NOT NULL, "role_id" uuid NOT NULL, CONSTRAINT "PK_23ed6f04fe43066df08379fd034" PRIMARY KEY ("user_id", "role_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_87b8888186ca9769c960e92687" ON "user_roles" ("user_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_b23c65e50a758245a33ee35fda" ON "user_roles" ("role_id") `);
        await queryRunner.query(`CREATE TABLE "role_permissions" ("role_id" uuid NOT NULL, "permission_id" uuid NOT NULL, CONSTRAINT "PK_25d24010f53bb80b78e412c9656" PRIMARY KEY ("role_id", "permission_id"))`);
        await queryRunner.query(`CREATE INDEX "IDX_178199805b901ccd220ab7740e" ON "role_permissions" ("role_id") `);
        await queryRunner.query(`CREATE INDEX "IDX_17022daf3f885f7d35423e9971" ON "role_permissions" ("permission_id") `);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_87b8888186ca9769c960e926870" FOREIGN KEY ("user_id") REFERENCES "users"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "user_roles" ADD CONSTRAINT "FK_b23c65e50a758245a33ee35fda1" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_178199805b901ccd220ab7740ec" FOREIGN KEY ("role_id") REFERENCES "roles"("id") ON DELETE CASCADE ON UPDATE CASCADE`);
        await queryRunner.query(`ALTER TABLE "role_permissions" ADD CONSTRAINT "FK_17022daf3f885f7d35423e9971e" FOREIGN KEY ("permission_id") REFERENCES "permissions"("id") ON DELETE NO ACTION ON UPDATE NO ACTION`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_17022daf3f885f7d35423e9971e"`);
        await queryRunner.query(`ALTER TABLE "role_permissions" DROP CONSTRAINT "FK_178199805b901ccd220ab7740ec"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_b23c65e50a758245a33ee35fda1"`);
        await queryRunner.query(`ALTER TABLE "user_roles" DROP CONSTRAINT "FK_87b8888186ca9769c960e926870"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_17022daf3f885f7d35423e9971"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_178199805b901ccd220ab7740e"`);
        await queryRunner.query(`DROP TABLE "role_permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_b23c65e50a758245a33ee35fda"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_87b8888186ca9769c960e92687"`);
        await queryRunner.query(`DROP TABLE "user_roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7d6df34265c2fae0e64979374d"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_24d1284269b70adadd4e9d9253"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_89a7d942bb1fc9e2989c032eca"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_28345c74f19456b00f80c1a9d2"`);
        await queryRunner.query(`DROP TABLE "ai_analysis_results"`);
        await queryRunner.query(`DROP TYPE "public"."ai_analysis_results_review_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."ai_analysis_results_analysis_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_7421efc125d95e413657efa3c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_177183f29f438c488b5e8510cd"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_cee5459245f652b75eb2759b4c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_2cd10fda8276bb995288acfbfb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_052f6905a83dedf0d5eeb5e69d"`);
        await queryRunner.query(`DROP TABLE "audit_logs"`);
        await queryRunner.query(`DROP TYPE "public"."audit_logs_action_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31c8776aa38d6fab44b2f34741"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4e2dc6d29a58fb59a9641c4133"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_4fef5beb624cd7bfd0f1401a94"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a77c28207a20aa2ad37ce5eca9"`);
        await queryRunner.query(`DROP TABLE "complaint_assignments"`);
        await queryRunner.query(`DROP TYPE "public"."complaint_assignments_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_e39f0fb6135bc98a2d60d965a0"`);
        await queryRunner.query(`DROP TABLE "complaint_status_history"`);
        await queryRunner.query(`DROP TYPE "public"."complaint_status_history_new_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."complaint_status_history_previous_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_010680569c7a7eee0a37801dd4"`);
        await queryRunner.query(`DROP TABLE "evidence_chain_of_custody"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_31e7823c6447bed65f6304d59b"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_71c5d63002a009be1366ed0632"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_1cfd367dd1275329cdc58b9024"`);
        await queryRunner.query(`DROP TABLE "evidence"`);
        await queryRunner.query(`DROP TYPE "public"."evidence_access_level_enum"`);
        await queryRunner.query(`DROP TYPE "public"."evidence_evidence_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c5f7adf7ff580617ee37583943"`);
        await queryRunner.query(`DROP TABLE "complaint_notes"`);
        await queryRunner.query(`DROP TABLE "complaint_categories_ref"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_0119fb6d3ef9bec0c4f3de4721"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_208ad761b4359509cd2f43da87"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_57f8030602f0e930c4c7b8a7bc"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_045cb646312f78bded6507fca5"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_dab6594090bc04d8ce83a997e8"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8c7495e1206503c359c41b6c96"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_af397ec1c0acdfeb72dc8e1fa0"`);
        await queryRunner.query(`DROP TABLE "complaints"`);
        await queryRunner.query(`DROP TYPE "public"."complaints_channel_enum"`);
        await queryRunner.query(`DROP TYPE "public"."complaints_source_enum"`);
        await queryRunner.query(`DROP TYPE "public"."complaints_category_enum"`);
        await queryRunner.query(`DROP TYPE "public"."complaints_severity_enum"`);
        await queryRunner.query(`DROP TYPE "public"."complaints_status_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_5332a4daa46fd3f4e6625dd275"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_92f5d3a7779be163cbea7916c6"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_aef1c7aef3725068e5540f8f00"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_77ee7b06d6f802000c0846f3a5"`);
        await queryRunner.query(`DROP TABLE "notifications"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_status_enum"`);
        await queryRunner.query(`DROP TYPE "public"."notifications_type_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_94fdca3c049f3b33844b9a03c8"`);
        await queryRunner.query(`DROP TABLE "complaint_officers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_f25c755da01b839dcf39b674ff"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_adcfd81394978d443ec6fe39d1"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a2e938acd9bad6c1834af39e19"`);
        await queryRunner.query(`DROP TABLE "officers"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_c0aea07014a01aa7ec7e1609f0"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_8f2f8bd600c9e1d07f8343a33c"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_43201337271442fa404765d7bb"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_d70989ea1ee2b4e6e5548fdb15"`);
        await queryRunner.query(`DROP TABLE "escalation_records"`);
        await queryRunner.query(`DROP TYPE "public"."escalation_records_reason_enum"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_66e88c2f16f4a8d3aa2321ea1a"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_830a5640e559f29067cc4985ac"`);
        await queryRunner.query(`DROP TABLE "police_stations"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_3ddc983c5f7bcf132fd8732c3f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_a7838d2ba25be1342091b6695f"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_ba3bd69c8ad1e799c0256e9e50"`);
        await queryRunner.query(`DROP TABLE "refresh_tokens"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_48ce552495d14eae9b187bb671"`);
        await queryRunner.query(`DROP TABLE "permissions"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_648e3f5447f725579d7d4ffdfb"`);
        await queryRunner.query(`DROP TABLE "roles"`);
        await queryRunner.query(`DROP INDEX "public"."IDX_97672ac88f789774dd47f7c8be"`);
        await queryRunner.query(`DROP TABLE "users"`);
    }

}
